CREATE TABLE RESERVIERUNGEN(
    ID INT NOT NULL AUTO_INCREMENT,
    BENUTZER INT DEFAULT 0,
    ZIMMER INT NOT NULL,
    AUS DATETIME DEFAULT CURRENT_TIMESTAMP, 
    BIS DATETIME DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY(ID)
);
